/**
 * Gemini Client Utility
 *
 * Provides configured Google Gemini AI client
 * with proper model selection and default settings
 */

import { GoogleGenerativeAI, GenerativeModel } from "@google/generative-ai";
import { logWarn } from "@/utils/logger.js";

/**
 * Default model configuration
 * Updated for Gemini 3+ models (July 2026)
 * See: https://ai.google.dev/gemini-api/docs/models/gemini
 */
export const DEFAULT_MODEL = "gemini-3.5-flash";
export const DEFAULT_MAX_TOKENS = 2048;
export const DEFAULT_TEMPERATURE = 1.0;

/**
 * Gemini client singleton
 */
let genAIClient: GoogleGenerativeAI | null = null;

/**
 * Get or create the Gemini AI client
 * @returns GoogleGenerativeAI client instance
 * @throws Error if GEMINI_API_KEY is not set
 */
export function getGeminiClient(): GoogleGenerativeAI {
    if (genAIClient) {
        return genAIClient;
    }

    const apiKey = process.env["GEMINI_API_KEY"];

    if (!apiKey) {
        throw new Error(
            "GEMINI_API_KEY environment variable is not set. " +
                "Please configure it in your .env file or Cloud Functions configuration.",
        );
    }

    genAIClient = new GoogleGenerativeAI(apiKey);
    return genAIClient;
}

/**
 * Get a configured generative model.
 * When running in the Firebase emulator (FUNCTIONS_EMULATOR=true) a local stub
 * is returned so that no real Gemini API key or quota is required.
 */
export function getGenerativeModel(modelName?: string): GenerativeModel {
    if (process.env["FUNCTIONS_EMULATOR"] === "true") {
        return createEmulatorStub();
    }
    const client = getGeminiClient();
    return client.getGenerativeModel({
        model: modelName ?? DEFAULT_MODEL,
    });
}

/**
 * Builds a GenerativeModel-compatible stub for local emulator runs.
 * Detects the operation from the request shape and returns plausible fake data:
 *   - JSON + "flashcard" in prompt → flashcard array
 *   - JSON (no "flashcard")        → tag array
 *   - plain text                   → summary string
 */
function createEmulatorStub(): GenerativeModel {
    return {
        generateContent: (request: unknown) => {
            const req = request as {
                contents?: { parts?: { text?: string }[] }[];
                generationConfig?: { responseMimeType?: string };
            };
            const prompt = req.contents?.[0]?.parts?.[0]?.text ?? "";
            const isJson =
                req.generationConfig?.responseMimeType === "application/json";
            const isFlashcards = isJson && /flashcard/i.test(prompt);

            let text: string;
            if (isFlashcards) {
                text = JSON.stringify([
                    {
                        front: "What is the main topic of this note?",
                        back: "A stub answer generated by the local emulator.",
                    },
                    {
                        front: "What are the key concepts covered?",
                        back: "These flashcards are produced by the emulator stub — no API key needed.",
                    },
                ]);
            } else if (isJson) {
                text = JSON.stringify(["stub-tag", "emulator", "local-dev"]);
            } else {
                text =
                    "This is a stub response from the local emulator. It simulates what the Gemini AI model would return for a real note.";
            }

            return Promise.resolve({
                response: {
                    text: () => text,
                    usageMetadata: { totalTokenCount: 0 },
                },
            });
        },
    } as unknown as GenerativeModel;
}

/**
 * Reset the client (useful for testing)
 */
export function resetGeminiClient(): void {
    genAIClient = null;
}

/**
 * Check if Gemini API is configured
 * @returns true if API key is available
 */
export function isGeminiConfigured(): boolean {
    const apiKey = process.env["GEMINI_API_KEY"];
    if (!apiKey) {
        logWarn("GEMINI_API_KEY is not configured");
        return false;
    }
    return true;
}
